spring.application.name=auth-service
server.port=${AUTH_SERVICE_PORT:8080}

# =========================
# DATABASE
# =========================
spring.datasource.url=${AUTH_DB_URL:jdbc:mysql://localhost:3306/finflow_auth_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:TanmoyPass4}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# =========================
# EUREKA
# =========================
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey}

# =========================
# LOGGING
# =========================
logging.level.com.example.demo=${LOG_LEVEL_APP:DEBUG}

# =========================
# SPRINGDOC / SWAGGER
# =========================
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/auth/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/auth/swagger-ui.html