spring.application.name=application-service
# ========================
# APPLICATION NAME (Eureka)
# ========================


# ========================
# SERVER PORT
# ========================
server.port=8081

# ========================
# EUREKA CONFIG
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ========================
# OPTIONAL (recommended)
# ========================
#eureka.instance.prefer-ip-address=true

# ========================
# LOGGING (debug JWT if needed)
# ========================
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/finflow_app_db
spring.datasource.username=root
spring.datasource.password=TanmoyPass4

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
logging.level.com.finflow.demo=DEBUG
spring.config.import=optional:configserver:http://localhost:8888
springdoc.override-with-generic-response=false

# =========================
# SWAGGER AGGREGATION (API GATEWAY)
# =========================

springdoc.swagger-ui.urls[0].name=application-service
springdoc.swagger-ui.urls[0].url=/application/v3/api-docs

springdoc.swagger-ui.urls[1].name=doc-verification
springdoc.swagger-ui.urls[1].url=/documents/v3/api-docs

springdoc.swagger-ui.urls[2].name=auth-service
springdoc.swagger-ui.urls[2].url=/auth/v3/api-docs

springdoc.swagger-ui.disable-swagger-default-url=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
