spring.application.name=doc-verification
server.port=8082

# DB config
spring.datasource.url=jdbc:mysql://localhost:3306/finflow_doc_db
spring.datasource.username=root
spring.datasource.password=TanmoyPass4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
