spring.application.name=config-server
server.port=${CONFIG_SERVER_PORT:8888}
spring.cloud.config.server.git.uri=${CONFIG_GIT_URI:https://github.com/TanmoyCodes/finflow-config}
spring.cloud.config.server.git.clone-on-start=true